In [87]:
!pip install giotto-ph

In [88]:
import gph
import numpy as np

points = np.random.randint(20, size=(20, 2))
points

array([[15,  4],
       [10, 14],
       [ 2,  2],
       [ 5, 11],
       [ 8,  3],
       [15, 19],
       [ 2,  8],
       [19,  2],
       [12, 16],
       [17, 10],
       [ 2,  6],
       [19, 12],
       [ 4,  8],
       [ 5,  2],
       [ 9, 18],
       [18, 12],
       [15, 18],
       [ 8,  7],
       [12,  1],
       [13, 15]])

In [89]:
output = gph.ripser_parallel(points, return_generators=True)
output

{'dgms': [array([[0.       , 1.       ],
         [0.       , 1.       ],
         [0.       , 1.4142135],
         [0.       , 2.       ],
         [0.       , 2.       ],
         [0.       , 2.236068 ],
         [0.       , 2.828427 ],
         [0.       , 3.       ],
         [0.       , 3.1622777],
         [0.       , 3.1622777],
         [0.       , 3.6055512],
         [0.       , 3.6055512],
         [0.       , 4.       ],
         [0.       , 4.       ],
         [0.       , 4.2426405],
         [0.       , 4.472136 ],
         [0.       , 4.472136 ],
         [0.       , 5.8309517],
         [0.       , 5.8309517],
         [0.       ,       inf]], dtype=float32),
  array([[6.3245554, 9.486833 ],
         [4.1231055, 6.0827627]], dtype=float32)],
 'gens': (array([[16, 16,  5],
         [15, 15, 11],
         [19, 19,  8],
         [12, 12,  6],
         [10, 10,  6],
         [11, 15,  9],
         [ 8,  8,  1],
         [13, 13,  2],
         [ 2, 13,  4],
         [ 6, 12

In [90]:
print("Persistance pairs: ")
print("H_0: ", output['dgms'][0])
print("H_1: ", output['dgms'][1])

Persistance pairs: 
H_0:  [[0.        1.       ]
 [0.        1.       ]
 [0.        1.4142135]
 [0.        2.       ]
 [0.        2.       ]
 [0.        2.236068 ]
 [0.        2.828427 ]
 [0.        3.       ]
 [0.        3.1622777]
 [0.        3.1622777]
 [0.        3.6055512]
 [0.        3.6055512]
 [0.        4.       ]
 [0.        4.       ]
 [0.        4.2426405]
 [0.        4.472136 ]
 [0.        4.472136 ]
 [0.        5.8309517]
 [0.        5.8309517]
 [0.              inf]]
H_1:  [[6.3245554 9.486833 ]
 [4.1231055 6.0827627]]


In [91]:
print(output['gens'][0])
print()
print(output['gens'][1])
print()
print(output['gens'][2])
print()
print(output['gens'][3])

[[16 16  5]
 [15 15 11]
 [19 19  8]
 [12 12  6]
 [10 10  6]
 [11 15  9]
 [ 8  8  1]
 [13 13  2]
 [ 2 13  4]
 [ 6 12  3]
 [ 1 19 16]
 [14 14  8]
 [17 17  4]
 [ 3 10  2]
 [18 18  0]
 [ 0 18  4]
 [ 7  7  0]
 [ 5 19 15]
 [ 4  3  1]]

[array([[ 9,  0, 17,  9],
       [17, 12, 17, 10]])]

[9]

[array([], shape=(0, 2), dtype=int64)]


In [92]:
print("Generators for corresponding pairs: ")
print("H_0: ")
for i in range(len(output['gens'][0])):
  print(output['gens'][0][i][0], ' ---> ', output['gens'][0][i][1:])
print("first number is the 'birth' vertex, second and third number are vertices of the edge that `killed' the topological feature for all FINITE bars in H_0 barcode\n\n")
for i in range(len(output['gens'][2])):
  print(output['gens'][2][i], ' ---> +infty')
print("first number is the 'birth' vertex for all IN_FINITE bars in H_0 barcode")


print("\n ----------------------------")

for i in range(len(output['gens'][1][0])):
  print(output['gens'][1][0][i][:2], ' ---> ', output['gens'][1][0][i][2:])
print("first two numbers are  vertices of the edge that 'created' topological feature, third and forth numbers are vertices of the edge that `killed' the topological feature for all FINITE bars in H_1 barcode")
for i in range(len(output['gens'][3])):
  print(output['gens'][3][i], ' ---> +infty')
print("first two numbers are  vertices of the edge that 'created' topological feature for all IN_FINITE bars in H_1 barcode")

Generators for corresponding pairs: 
H_0: 
16  --->  [16  5]
15  --->  [15 11]
19  --->  [19  8]
12  --->  [12  6]
10  --->  [10  6]
11  --->  [15  9]
8  --->  [8 1]
13  --->  [13  2]
2  --->  [13  4]
6  --->  [12  3]
1  --->  [19 16]
14  --->  [14  8]
17  --->  [17  4]
3  --->  [10  2]
18  --->  [18  0]
0  --->  [18  4]
7  --->  [7 0]
5  --->  [19 15]
4  --->  [3 1]
first number is the 'birth' vertex, second and third number are vertices of the edge that `killed' the topological feature for all FINITE bars in H_0 barcode


9  ---> +infty
first number is the 'birth' vertex for all IN_FINITE bars in H_0 barcode

 ----------------------------
[9 0]  --->  [17  9]
[17 12]  --->  [17 10]
first two numbers are  vertices of the edge that 'created' topological feature, third and forth numbers are vertices of the edge that `killed' the topological feature for all FINITE bars in H_1 barcode
[]  ---> +infty
first two numbers are  vertices of the edge that 'created' topological feature for all IN

In [93]:
import numpy as np

H0_birth = np.zeros(points.shape[0], dtype=int)
H0_death = np.zeros((points.shape[0], 2), dtype=int)

H1_birth = np.zeros((points.shape[0], 2), dtype=int)
H1_death = np.zeros((points.shape[0], 2), dtype=int)

# Iterate over finite generators for H0
for i in range(len(output['gens'][0])):
    birth_vertex = output['gens'][0][i][0]
    death_vertices = output['gens'][0][i][1:]

    H0_birth[birth_vertex] = 1
    H0_death[death_vertices[0], 0] = 1
    H0_death[death_vertices[1], 1] = 1

# Iterate over finite generators for H0
for i in range(len(output['gens'][2])):
    birth_vertex = output['gens'][2][i]

    H0_birth[birth_vertex] = 1

# Iterate over finite generators for H1
for i in range(len(output['gens'][1][0][:2])):
    birth_vertices = output['gens'][1][0][i][:2]
    death_vertices = output['gens'][1][0][i][2:]

    H1_birth[birth_vertices[0], 0] = 1
    H1_birth[birth_vertices[1], 1] = 1
    H1_death[death_vertices[0], 0] = 1
    H1_death[death_vertices[1], 1] = 1

# Iterate over finite generators for H1
for i in range(len(output['gens'][3])):
    birth_vertex = output['gens'][3][i]

    H1_birth[birth_vertices[0], 0] = 1
    H1_birth[birth_vertices[0], 0] = 1

In [94]:
import pandas as pd

# Assuming x_coords and y_coords are arrays containing x and y coordinates respectively
data = {'x': points[:, 0], 'y': points[:, 1]}

# Convert H0_birth, H0_death, H1_birth, H1_death to DataFrame
df_H0_birth = pd.DataFrame(H0_birth, columns=['H0_birth'])
df_H0_death = pd.DataFrame(H0_death, columns=['H0_death_1', 'H0_death_2'])
df_H1_birth = pd.DataFrame(H1_birth, columns=['H1_birth_1', 'H1_birth_2'])
df_H1_death = pd.DataFrame(H1_death, columns=['H1_death_1', 'H1_death_2'])

# Concatenate all DataFrames
df = pd.concat([pd.DataFrame(data), df_H0_birth, df_H0_death, df_H1_birth, df_H1_death], axis=1)

# Display the DataFrame
df


x   y  H0_birth  H0_death_1  H0_death_2  H1_birth_1  H1_birth_2  \
0   15   4         1           0           1           0           1   
1   10  14         1           0           1           0           0   
2    2   2         1           0           1           0           0   
3    5  11         1           1           1           0           0   
4    8   3         1           0           1           0           0   
5   15  19         1           0           1           0           0   
6    2   8         1           0           1           0           0   
7   19   2         1           1           0           0           0   
8   12  16         1           1           1           0           0   
9   17  10         1           0           1           1           0   
10   2   6         1           1           0           0           0   
11  19  12         1           0           1           0           0   
12   4   8         1           1           0           0           1   
13   5   2         1           1           0           0           0   
14   9  18         1           1           0           0           0   
15  18  12         1           1           1           0           0   
16  15  18         1           1           1           0           0   
17   8   7         1           1           0           1           0   
18  12   1         1           1           0           0           0   
19  13  15         1           1           0           0           0   

    H1_death_1  H1_death_2  
0            0           0  
1            0           0  
2            0           0  
3            0           0  
4            0           0  
5            0           0  
6            0           0  
7            0           0  
8            0           0  
9            0           1  
10           0           1  
11           0           0  
12           0           0  
13           0           0  
14           0           0  
15           0           0  
16           0           0  
17           1           0  
18           0           0  
19           0           0